### ISSUE TITLE
Multiple Discovery Servers 

### ISSUE THREAD

**Issue by Jimmy316** [eProsima/Discovery-Server#9]
Hi 

Rather than an issue I have a quick question. I would like to setup a cluster with multiple Discovery Servers. I wanted to understand how this would work. 

1. Would all the servers have visibility into all the participants and their subscribers/publishers? So if one of the servers goes down the other server can act as a backup.
2. Can the participants use get multiple Discovery Server configurations in this case?

Thanks 

--
Jimmy

**Comment by richiware** [comment]
I will try to answer your questions

>1. Would all the servers have visibility into all the participants and their subscribers/publishers? So if one of the 
>servers goes down the other server can act as a backup.

You can configure each participant to connect several discovery servers. A discovery server has knowledge about all 
participants (and their entities) connected to it. Therefore, if a discovery server goes down, the rest of discovery 
servers will maintain the discovery mechanism.

>2. Can the participants use get multiple Discovery Server configurations in this case?

If I understand the question correctly, yes, a participant can be configured to connect to several discovery servers.


I hope I was helpful.

↪ 2020-01-03 vie 18:08, Jimmy Bhaktha <notifications@github.com>:

**Comment by Jimmy316** [comment]
Hi Richie 

Thanks answering my questions.

**Comment by Jimmy316** [comment]
Hi Richiware 

I am not sure if you are the person to answer this but I had a another issue with Discovery Server 
https://github.com/eProsima/Fast-RTPS/issues/941. If you can help answer them would be great.

--
Jimmy
